# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := box_intersect test_player test_terrain test_quad

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

box_intersect: 
	@echo "==== Building box_intersect ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f box_intersect.make

test_player: 
	@echo "==== Building test_player ($(config)) ===="
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_player.make

test_terrain: 
	@echo "==== Building test_terrain ($(config)) ===="
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_terrain.make

test_quad: 
	@echo "==== Building test_quad ($(config)) ===="
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_quad.make

clean:
	@${MAKE} --no-print-directory -C . -f box_intersect.make clean
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_player.make clean
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_terrain.make clean
	@${MAKE} --no-print-directory -C projet-mmachine/build -f test_quad.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   box_intersect"
	@echo "   test_player"
	@echo "   test_terrain"
	@echo "   test_quad"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
